# Generated by Django 5.2 on 2025-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0008_cart_cartitem_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='related_threads',
            field=models.ManyToManyField(blank=True, to='mainaccount.thread'),
        ),
    ]
