# Generated by Django 5.2 on 2025-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0009_thread_related_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan Kategori'),
        ),
        migrations.AddField(
            model_name='category',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Hover Resim'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Ana Resim'),
        ),
    ]
