# Generated by Django 5.2 on 2025-05-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0011_sellerprofile_product_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainaccount.product'),
        ),
    ]
