# Generated by Django 5.2 on 2025-05-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0012_thread_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='product',
        ),
        migrations.AddField(
            model_name='thread',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='threads', to='mainaccount.product'),
        ),
    ]
