# Generated by Django 5.2 on 2025-05-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0016_productreview_image_productreview_seller_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainaccount.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='products',
            field=models.ManyToManyField(blank=True, to='mainaccount.product'),
        ),
    ]
