# Generated by Django 5.2 on 2025-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0017_order_coupon_order_coupon_used_thread_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
