# Generated by Django 5.2 on 2025-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0018_order_discount_amount_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercouponreward',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
