# Generated by Django 5.2 on 2025-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0019_usercouponreward_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forumcategory_images/'),
        ),
    ]
