# Generated by Django 5.2 on 2025-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccount', '0020_forumcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
    ]
